//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppTester.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StringCollection", Namespace="http://nlog-project.org/ws/", ItemName="l")]
    [System.SerializableAttribute()]
    public class StringCollection : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nlog-project.org/ws/", ConfigurationName="ServiceReference1.ILogReceiverServer")]
    public interface ILogReceiverServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlog-project.org/ws/ILogReceiverServer/ProcessLogMessages", ReplyAction="http://nlog-project.org/ws/ILogReceiverServer/ProcessLogMessagesResponse")]
        void ProcessLogMessages(NLog.LogReceiverService.NLogEvents events);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogReceiverServerChannel : ConsoleAppTester.ServiceReference1.ILogReceiverServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogReceiverServerClient : System.ServiceModel.ClientBase<ConsoleAppTester.ServiceReference1.ILogReceiverServer>, ConsoleAppTester.ServiceReference1.ILogReceiverServer {
        
        public LogReceiverServerClient() {
        }
        
        public LogReceiverServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogReceiverServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogReceiverServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogReceiverServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessLogMessages(NLog.LogReceiverService.NLogEvents events) {
            base.Channel.ProcessLogMessages(events);
        }
    }
}
